const grid = getByClass('grid-project-img');
const gridImgAssign = (img, src) => (img.src = src);
gridImgAssign(grid[0], google.src);
gridImgAssign(grid[1], tribute.src);
gridImgAssign(grid[2], calTube.src);
gridImgAssign(grid[3], saas.src);
gridImgAssign(grid[4], responsive.src);
gridImgAssign(grid[5], pokemon.src);
gridImgAssign(grid[6], favz.src);
gridImgAssign(grid[7], logins.src);
